apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyline-app
  labels:
    app: skyline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skyline
  template:
    metadata:
      labels:
        app: skyline
    spec:
      containers:
      - name: skyline
        image: your-registry/skyline:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: skyline-db-secret
              key: DB_HOST
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: skyline-db-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: skyline-db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skyline-db-secret
              key: DB_PASSWORD
        - name: DB_CONNECTION_POOL_SIZE
          value: "10"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"